import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import AuthProviders from "@/components/Providers/AuthProviders"
import Appbar from "@/components/Layout/Appbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next-Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProviders>
          <Appbar />
          <div className='bg-slate-50 w-full h-screen p-10 flex justify-center items-center'>
            {children}
          </div>
        </AuthProviders>
      </body>
    </html>
  );
}
